<div class="MilestoneDetails" id="Milestone{{m.id}}" 
     style="padding-left:58px; display:none; clear:both; margin:12px 0px; position:relative; top:12px;">
    <table width="100%" cellspacing="0" cellpadding="0">
        <tr>
            <td width="100%" valign="top">
                <table class="CForm_Table TableFormGroup">
                    <tr>
                        <td align="right" class="CForm_Name" valign="top"><b>Name</b>&nbsp;</td>
                        <td class="CForm_Value" valign="top">
                            <input type="text" name="Name" id="Name" value="{{m.name}}" title="Please enter a Name" class="CForm_Textbox"/>
                        </td>
                    </tr>
                    <tr>
                        <td align="right" class="CForm_Name" valign="top"><b>Customer Approval:</b>&nbsp;</td>
                        <td class="CForm_Value" valign="top">
                            <div class="CForm_OnOff" id="CustomerApproval{{m.id}}_YesNo"></div>
                            <input type="hidden" id="CustomerApproval{{m.id}}" value="{{m.customerApproval}}"/>
                            <script language="Javascript">
                                CForm.AddYesNoControl('CustomerApproval{{m.id}}_YesNo', 'CustomerApproval{{m.id}}');
                             </script>
                        </td>
                    </tr>
                    <tr>
                        <td align="right" class="CForm_Name" valign="top"><b>Summary</b>&nbsp;</td>
                        <td class="CForm_Value" valign="top">
                            <textarea name="Summary{{m.id}}" id="Summary{{m.id}}" class="CForm_Textarea">{{m.summary}}</textarea>
                        </td>
                    </tr>
                    <tr>
                        <td align="right" class="CForm_Name" valign="top"><b>Estimated Start Date</b>&nbsp;</td>
                        <td class="CForm_Value" valign="top">
                            <input type="text" name="EstimatedStartDate{{m.id}}" id="EstimatedStartDate{{m.id}}" 
                                   class="CForm_Datepicker" readonly="readonly" value="{{m.estimatedStartDate}}"/></td>
                        <script type="text/javascript">
                            $(document).ready(function(){
                                $("#" + 'EstimatedStartDate{{m.id}}').datepicker( {
                                    showOn:				'both',
                                    buttonImageOnly:	true,
                                    buttonText:			'',
                                    dateFormat:			'MM d, yy',
                                    minDate:			new Date('', 0, 1),
                                    maxDate:			new Date('', 0, 1)
                                });
                            });
                        </script>
                    </tr>
                    <tr>
                        <td align="right" class="CForm_Name" valign="top"><b>Expected Delivery Date</b>&nbsp;</td>
                        <td class="CForm_Value" valign="top">
                            <input type="text" name="ExpectedDeliveryDate{{m.id}}" id="ExpectedDeliveryDate{{m.id}}" 
                                   class="CForm_Datepicker" readonly="readonly" value="{{m.expectedDeliveryDate}}"/></td>
                        <script type="text/javascript">
                            $(document).ready(function(){
                                $("#" + 'ExpectedDeliveryDate{{m.id}}').datepicker( {
                                    showOn:				'both',
                                    buttonImageOnly:	true,
                                    buttonText:			'',
                                    dateFormat:			'MM d, yy',
                                    minDate:			new Date('', 0, 1),
                                    maxDate:			new Date('', 0, 1)
                                });
                            });
                        </script>
                    </tr>
                    <tr>
                        <td align="right" class="CForm_Name" valign="top"><b>Actual Delivery Date</b>&nbsp;</td>
                        <td class="CForm_Value" valign="top">
                            <input type="text" name="ActualDeliveryDate{{m.id}}" id="ActualDeliveryDate{{m.id}}" 
                                   class="CForm_Datepicker" readonly="readonly" value="{{m.actualDeliveryDate}}"/></td>
                        <script type="text/javascript">
                            $(document).ready(function(){
                                $("#" + 'ActualDeliveryDate{{m.id}}').datepicker( {
                                    showOn:				'both',
                                    buttonImageOnly:	true,
                                    buttonText:			'',
                                    dateFormat:			'MM d, yy',
                                    minDate:			new Date('', 0, 1),
                                    maxDate:			new Date('', 0, 1)
                                });
                            });
                        </script>
                    </tr>
        <!--
            echo CForm::AddTextbox("Name", "Name", $Milestone->Name, "Please enter a Name");
            echo CForm::AddYesNo("Customer Approval", "CustomerApproval", $Milestone->CustomerApproval, "YesNo");
            echo CForm::AddTextarea("Summary", "Summary", $Milestone->Summary);
            echo CForm::AddDatepicker("Estimated Start Date", "EstimatedStartDate", ($Milestone->EstimatedStartDate > 0 ? $Milestone->EstimatedStartDate : ""), "", "");
            echo CForm::AddDatepicker("Expected Delivery Date", "ExpectedDeliveryDate", ($Milestone->ExpectedDeliveryDate > 0 ? $Milestone->ExpectedDeliveryDate : ""), "", "", "Please enter an Expected Delivery Date");
            echo CForm::AddDatepicker("Actual Delivery Date", "ActualDeliveryDate", ($Milestone->ActualDeliveryDate > 0 ? $Milestone->ActualDeliveryDate : ""), "", "");
            echo CForm::AddTextbox("Plant Allocated", "PlantAllocated", $Milestone->PlantAllocated);
            echo CForm::AddDropdown("Assigned To", "AssignedTo", $Users, $Milestone->AssignedTo);	
            echo CForm::AddYesNo("Complete", "Status", $Milestone->IsComplete(), "YesNo");
            echo CForm::AddHidden("ProjectsID", $ProjectID);
            echo CForm::AddHidden("MilestoneID", $Milestone->ID);
        -->
    </table>
</td>
</tr>
<tr>
    <td colspan="3" align="right">
        <input type="hidden" value="0" name="ID" id="ID"/>
        <div class="Button" value="Save" onClick="MProjects.AddMilestone();">save</div>
        <div class="Button" value="Cancel" onClick="MProjects.ViewDetails();">cancel</div>
        <div class="Button" value="Delete" onClick="MProjects.DeleteMilestone();">delete</div>
    </td>
</tr>
</table>
</div>